apiVersion: apps/v1 # The API version for Deployment objects
kind: Deployment # The type of Kubernetes object
metadata:
  name: apache-deployment # Name of the deployment
  labels:
    app: webserver
spec:
  replicas: 3 # Number of desired pods
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver # Labels to match with the selector
    spec:
      containers:
      - name: apache-container
        image: httpd:latest # Specifies the container image and tag
        ports:
        - containerPort: 80 # The port the container exposes
